// Package server wires up the RideNow HTTP router, middleware, and handlers.
package server

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"

	"github.com/ridenow/ridenow/internal/db"
)

// Server holds application dependencies and the HTTP router.
type Server struct {
	db     *sql.DB
	store  *db.Store
	router chi.Router
}

// New constructs a Server with middleware and routes wired up.
func New(database *sql.DB) *Server {
	s := &Server{
		db:     database,
		store:  db.NewStore(database),
		router: chi.NewRouter(),
	}
	s.routes()
	return s
}

// ServeHTTP lets Server satisfy http.Handler.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	s.router.ServeHTTP(w, r)
}

func (s *Server) routes() {
	s.router.Use(middleware.RequestID)
	s.router.Use(middleware.RealIP)
	s.router.Use(middleware.Logger)
	s.router.Use(middleware.Recoverer)

	s.router.Get("/healthz", s.handleHealth)
	s.router.Get("/livez", s.handleLive)
	s.router.Post("/rides", s.handleCreateRide)
	s.router.Get("/rides/{id}", s.handleGetRide)
}

// healthResponse is the body returned by GET /healthz, which is a combined
// liveness+readiness probe: 200 {"status":"ok","db":"ok"} when the database is
// reachable, 503 {"status":"degraded","db":"unreachable"} when the ping fails.
// The two-field {status,db} schema is a locked public contract — the db field
// is a deliberate deploy/readiness signal — so do not reduce or extend it
// without a versioned change.
type healthResponse struct {
	Status string `json:"status"`
	DB     string `json:"db"`
}

// handleHealth reports liveness and readiness, including a database ping.
func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {
	resp := healthResponse{Status: "ok", DB: "ok"}
	code := http.StatusOK

	ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
	defer cancel()
	if err := s.db.PingContext(ctx); err != nil {
		resp.Status = "degraded"
		resp.DB = "unreachable"
		code = http.StatusServiceUnavailable
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	if err := json.NewEncoder(w).Encode(resp); err != nil {
		log.Printf("health: encode response: %v", err)
	}
}

// handleLive is a dependency-free liveness probe. It reports only that the
// process is running and never pings the database, so a transient DB outage
// drains this instance from rotation via the readiness probe (/healthz) instead
// of tripping a Kubernetes liveness probe into a restart loop that cannot heal
// the database and only amplifies the outage. Deployments should point their
// liveness probe at /livez and their readiness probe at /healthz.
func (s *Server) handleLive(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(map[string]string{"status": "ok"}); err != nil {
		log.Printf("live: encode response: %v", err)
	}
}

// maxCreateRideBody bounds the POST /rides request body to guard against a
// large-payload denial of service on the create endpoint.
const maxCreateRideBody = 1 << 20 // 1 MiB

// createRideRequest is the client-supplied payload for POST /rides. It
// deliberately exposes only the fields a client may set; id, status, and
// created_at are always generated server-side, so a client cannot forge or
// mass-assign server-owned state.
type createRideRequest struct {
	Rider       string `json:"rider"`
	Origin      string `json:"origin"`
	Destination string `json:"destination"`
}

// handleCreateRide persists a ride from the request body and returns it.
// Only rider/origin/destination are accepted from the client; id, status,
// and created_at are generated by the Store.
func (s *Server) handleCreateRide(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, maxCreateRideBody)

	var req createRideRequest
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		http.Error(w, "invalid request body", http.StatusBadRequest)
		return
	}

	if req.Rider == "" || req.Origin == "" || req.Destination == "" {
		http.Error(w, "rider, origin, and destination are required", http.StatusBadRequest)
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	created, err := s.store.Create(ctx, db.Ride{
		Rider:       req.Rider,
		Origin:      req.Origin,
		Destination: req.Destination,
	})
	if err != nil {
		log.Printf("rides: create: %v", err)
		http.Error(w, "could not create ride", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if err := json.NewEncoder(w).Encode(created); err != nil {
		log.Printf("rides: encode response: %v", err)
	}
}

// handleGetRide returns a persisted ride by id, or 404 if it is unknown.
func (s *Server) handleGetRide(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	ride, err := s.store.Get(ctx, id)
	if errors.Is(err, db.ErrNotFound) {
		http.Error(w, "ride not found", http.StatusNotFound)
		return
	}
	if err != nil {
		log.Printf("rides: get: %v", err)
		http.Error(w, "could not fetch ride", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(ride); err != nil {
		log.Printf("rides: encode response: %v", err)
	}
}
