// Package server wires up the RideNow HTTP router, middleware, and handlers.
package server

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"

	"github.com/ridenow/ridenow/internal/auth"
	"github.com/ridenow/ridenow/internal/db"
	"github.com/ridenow/ridenow/internal/driver"
	"github.com/ridenow/ridenow/internal/rider"
	"github.com/ridenow/ridenow/internal/trip"
)

// Server holds application dependencies and the HTTP router. It is the
// composition root of the modular monolith: it owns the shared *sql.DB pool
// and constructs each bounded-context service (auth at the transport edge;
// rider, driver, and trip in the domain).
type Server struct {
	db     *sql.DB
	store  *db.Store
	auth   *auth.Service
	rider  *rider.Service
	driver *driver.Service
	trip   *trip.Service
	router chi.Router
}

// New constructs a Server with middleware and routes wired up.
func New(database *sql.DB) *Server {
	store := db.NewStore(database)
	r := rider.New()
	d := driver.New()
	s := &Server{
		db:     database,
		store:  store,
		auth:   auth.New(),
		rider:  r,
		driver: d,
		trip:   trip.New(store, r, d),
		router: chi.NewRouter(),
	}
	s.routes()
	return s
}

// ServeHTTP lets Server satisfy http.Handler.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	s.router.ServeHTTP(w, r)
}

func (s *Server) routes() {
	s.router.Use(middleware.RequestID)
	s.router.Use(middleware.RealIP)
	s.router.Use(middleware.Logger)
	s.router.Use(middleware.Recoverer)

	s.router.Get("/healthz", s.handleHealth)
	s.router.Post("/rides", s.handleCreateRide)
	s.router.Get("/rides/{id}", s.handleGetRide)

	// Protected routes: auth.Middleware validates the bearer token and injects
	// the caller identity before any trip domain code runs, enforcing auth at
	// the transport boundary.
	s.router.Group(func(r chi.Router) {
		r.Use(auth.Middleware(s.auth))
		r.Post("/trips", s.handleCreateTrip)
	})
}

type healthResponse struct {
	Status string `json:"status"`
	DB     string `json:"db"`
}

// handleHealth reports liveness and readiness, including a database ping.
func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {
	resp := healthResponse{Status: "ok", DB: "ok"}
	code := http.StatusOK

	ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
	defer cancel()
	if err := s.db.PingContext(ctx); err != nil {
		resp.Status = "degraded"
		resp.DB = "unreachable"
		code = http.StatusServiceUnavailable
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	if err := json.NewEncoder(w).Encode(resp); err != nil {
		log.Printf("health: encode response: %v", err)
	}
}

// maxCreateRideBody bounds the POST /rides request body to guard against a
// large-payload denial of service on the create endpoint.
const maxCreateRideBody = 1 << 20 // 1 MiB

// createRideRequest is the client-supplied payload for POST /rides. It
// deliberately exposes only the fields a client may set; id, status, and
// created_at are always generated server-side, so a client cannot forge or
// mass-assign server-owned state.
type createRideRequest struct {
	Rider       string `json:"rider"`
	Origin      string `json:"origin"`
	Destination string `json:"destination"`
}

// handleCreateRide persists a ride from the request body and returns it.
// Only rider/origin/destination are accepted from the client; id, status,
// and created_at are generated by the Store.
func (s *Server) handleCreateRide(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, maxCreateRideBody)

	var req createRideRequest
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		http.Error(w, "invalid request body", http.StatusBadRequest)
		return
	}

	if req.Rider == "" || req.Origin == "" || req.Destination == "" {
		http.Error(w, "rider, origin, and destination are required", http.StatusBadRequest)
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	created, err := s.store.Create(ctx, db.Ride{
		Rider:       req.Rider,
		Origin:      req.Origin,
		Destination: req.Destination,
	})
	if err != nil {
		log.Printf("rides: create: %v", err)
		http.Error(w, "could not create ride", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if err := json.NewEncoder(w).Encode(created); err != nil {
		log.Printf("rides: encode response: %v", err)
	}
}

// createTripRequest is the client-supplied payload for POST /trips. The rider
// identity is not accepted from the body: it is resolved from the bearer token
// by auth.Middleware, so a client cannot request a trip on another rider's
// behalf.
type createTripRequest struct {
	DriverID string `json:"driver_id"`
}

// handleCreateTrip requests a trip for the authenticated rider. The rider id
// comes from the request context (populated by auth.Middleware); only the
// driver id is read from the body. It delegates rider/driver validation and
// persistence to the trip service and maps domain validation errors to 400.
func (s *Server) handleCreateTrip(w http.ResponseWriter, r *http.Request) {
	riderID, ok := auth.UserIDFrom(r.Context())
	if !ok {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}

	r.Body = http.MaxBytesReader(w, r.Body, maxCreateRideBody)

	var req createTripRequest
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		http.Error(w, "invalid request body", http.StatusBadRequest)
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	created, err := s.trip.Request(ctx, riderID, req.DriverID)
	if errors.Is(err, rider.ErrInvalidRider) || errors.Is(err, driver.ErrInvalidDriver) {
		http.Error(w, "invalid rider or driver", http.StatusBadRequest)
		return
	}
	if err != nil {
		log.Printf("trips: request: %v", err)
		http.Error(w, "could not create trip", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if err := json.NewEncoder(w).Encode(created); err != nil {
		log.Printf("trips: encode response: %v", err)
	}
}

// handleGetRide returns a persisted ride by id, or 404 if it is unknown.
func (s *Server) handleGetRide(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	ride, err := s.store.Get(ctx, id)
	if errors.Is(err, db.ErrNotFound) {
		http.Error(w, "ride not found", http.StatusNotFound)
		return
	}
	if err != nil {
		log.Printf("rides: get: %v", err)
		http.Error(w, "could not fetch ride", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(ride); err != nil {
		log.Printf("rides: encode response: %v", err)
	}
}
